### ISSUE TITLE
What's meaning of 'prior' in nn.init.constant_(self.cls_logits.bias,-math.log((1 - prior) / prior)) in head.py

### ISSUE THREAD

**Issue by zlq1997** [ChingHo97/FCOS-PyTorch-37.2AP#15]
Does it has same meaning with score_threshold in eval_voc.py?

**Comment by zhenghao977** [comment]
No, this is just an experience for initialization of the classfication head.

**Comment by zlq1997** [comment]
> No, this is just an experience for initialization of the classfication head.

Thank you!
