### ISSUE TITLE
关于代码中的小细节

### ISSUE THREAD

**Issue by dongdongyee** [ChingHo97/FCOS-PyTorch-37.2AP#16]
非常感谢您分享代码！有个小问题向您请教
https://github.com/zhenghao977/FCOS-PyTorch-37.2AP/blob/2bfa4b6ca57358f52f7bc7b44f506608e99894e6/model/fcos.py#L83
1. fcos.py的forward函数 line83中为何要对classes做+1处理？
2. 还是这个函数， 为什么没有过滤掉背景标签对应的boxes和scores？
期待您的回复！感谢！

**Comment by zhenghao977** [comment]
1.请注意查看dataset中不管是pascal还是coco id都是从1开始的，实际channel下标是从0开始的，所以需要加1.
2.没有显示定义背景类，没有背景标签，对于没有foreground的pixel，所有channel的output均接近于0，通过阈值判定为background。

**Comment by dongdongyee** [comment]
非常感谢您的解答！
