### ISSUE TITLE
0it [00:00, ?it/s]

### ISSUE THREAD

**Issue by shaojiestar** [ChingHo97/FCOS-PyTorch-37.2AP#2]
when I give the COCOGenerator the path of coco test2017 and image_info_test-dev2017.json.the coco_eval.py can't run normally。and there are not error info
when I add a line to show the len of generator,it's 0
below is the output of the terminal:
(BorderDet) PS \FCOS-PyTorch-37.2AP-master> python -u "\FCOS-PyTorch-37.2AP-master\coco_eval.py"
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
INFO====>check annos, filtering invalid data......
INFO===>success frozen BN
INFO===>success frozen backbone stage1
0
0it [00:00, ?it/s]

**Comment by ChingHo97** [comment]
I didn't meet this problem, in my env, the codes run well. I suggest you check your json file.

**Comment by shaojiestar** [comment]
I have solved this problem.there are no annitions in MS COCO test-dev dataset.So the program can't read any annitions in the json file. In the end, I just revise your code so that I can predict the images in test-dev and generate the json file.Then I upload this test-dev result json file to the MS COCO detection(bbox) evaluation server,I get the map(@0.5.0.95)=0.384

**Comment by ChingHo97** [comment]
I see. the ap which is  a little lower than paper may because of the difference of the post-processing.
