### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by chuzcjoe** [ChingHo97/FCOS-PyTorch-37.2AP#3]
Hi, I am using the pretrained voc weights, and it turns out that class outputs contain indexes out of range(it is supposed to be from 0-20). I am not sure if you uploaded a wrong weight file or not.

**Comment by ChingHo97** [comment]
@chuzcjoe  The pretrained voc weights file is not wrong. FCOS outputs' class indexes are in range of [1,20] （total 20）because  I set 0 as background, so in detect.py, the colormap's index should be class indexes -1 . I have fixed this bug, really thank you.

**Comment by chuzcjoe** [comment]
> @chuzcjoe The pretrained voc weights file is not wrong. FCOS outputs' class indexes are in range of [1,20] （total 20）because I set 0 as background, so in detect.py, the colormap's index should be class indexes -1 . I have fixed this bug, really thank you.

In the provided voc weights, i believe the classifier head has channel size of 80 instead of 20. You can double-check it.

**Comment by chuzcjoe** [comment]
> @chuzcjoe The pretrained voc weights file is not wrong. FCOS outputs' class indexes are in range of [1,20] （total 20）because I set 0 as background, so in detect.py, the colormap's index should be class indexes -1 . I have fixed this bug, really thank you.

Hi, I figured it out. Thanks!
